# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - go run .
  build:
    cmds:
      - rm -rf dist
      - mkdir -p dist
      - go build -ldflags '-w -s' -trimpath -o dist .